---
minimum_pre_commit_version: "1.15"
default_stages: [commit]

ci:
  skip: []

repos:
  # ----------------------------------------------
  # Meta hooks
  # ----------------------------------------------

  - repo: meta
    hooks:
      - id: identity
        stages: [manual]
      - id: check-hooks-apply
        stages: [manual]
      - id: check-useless-excludes
        stages: [manual]

  # ####################################################################################
  #
  #       FORMATTING
  #
  # ####################################################################################

  # ----------------------------------------------
  # General (code unspecific)
  # ----------------------------------------------

  # code unspecific out-of-the-box hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 38b88246ccc552bffaaf54259d064beeee434539 # frozen: v4.0.1
    hooks:
      - id: end-of-file-fixer
        stages: [commit]
      - id: trailing-whitespace
        stages: [commit]

  # ----------------------------------------------
  # Rust
  # ----------------------------------------------

  # Run rust toolchain
  - repo: local
    hooks:
      # rustfmt - rust formater
      # Config file: rustfmt.toml
      - id: cargo-fmt
        name: rustfmt
        description: Format rust source with rustfmt.
        entry: cargo fmt
        args: ["--"]
        language: system
        types: [rust]

  # ----------------------------------------------
  # JS / TS / HTML / CSS / MD / JSON / YAML
  # ----------------------------------------------

  # prettier - JS formater
  - repo: https://github.com/pre-commit/mirrors-prettier
    # https://github.com/prettier/prettier
    # Config file: .prettierrc (JSON, YAML)
    # Ignore file: .prettierignore (file ignore pattern)
    rev: a99a3fbe79a9d346cabd02a5e167ad0edafe616b # frozen: v2.3.0
    hooks:
      - id: prettier

  # ####################################################################################
  #
  #       LINTING
  #
  # ####################################################################################

  # ----------------------------------------------
  # General (code unspecific)
  # ----------------------------------------------

  - repo: local
    hooks:
      # Find TODO:|FIXME:|BUG: comments in all files
      # Inline skip: `#i#` directly after the colon after the tag-word
      - id: find-todos
        name: "Find TODO:|FIXME:|BUG: comments"
        description: "Check for TODO:|FIXME:|BUG: comments in all files"
        language: pygrep
        entry: '(^|//!?|#|<!--|;|/\*(\*|!)?|\.\.)\s*(TODO:|FIXME:|BUG:)(?!#i#)'
        exclude: TODO

  # code unspecific out-of-the-box hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 38b88246ccc552bffaaf54259d064beeee434539 # frozen: v4.0.1
    hooks:
      - id: check-case-conflict
      - id: check-shebang-scripts-are-executable
        exclude: '^.*\.rs$'
      - id: detect-private-key

  # ----------------------------------------------
  # Rust
  # ----------------------------------------------

  # Run rust toolchain
  - repo: local
    hooks:
      # clippy - rust linter
      - id: cargo-clippy
        name: clippy
        description: Lint rust source with clippy.
        entry: cargo clippy
        language: system
        types: [rust]
        pass_filenames: false
      # check - rust package checker
      - id: cargo-check
        name: cargo check
        description: Check rust package for errors.
        entry: cargo check
        args: ["--all-targets"]
        language: system
        types: [rust]
        pass_filenames: false

  # ----------------------------------------------
  # JSON / TOML / YAML
  # ----------------------------------------------

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 38b88246ccc552bffaaf54259d064beeee434539 # frozen: v4.0.1
    hooks:
      - id: check-json
      - id: check-toml
      - id: check-yaml

  # yamllint - yaml linter
  - repo: https://github.com/adrienverge/yamllint
    rev: 85ccd625a382423edd988fcb796c4dd5897886fb # frozen: v1.26.1
    hooks:
      # Config file: .yamllint (yaml) [--config-file]
      # Inline skip: `# yamllint disable-line[ rule:<RULE>]`
      # Block skip: `# yamllint disable[ rule:<RULE>]`
      # Block skip end: `# yamllint enable`
      - id: yamllint
